# Generated by Django 5.2 on 2025-04-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_students_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
