# Generated by Django 5.2 on 2025-04-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_students_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=500)),
                ("speed", models.IntegerField(default=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
